version: "3.9"
services:
  virtuoso:
    image: openlink/virtuoso-opensource-7:latest
    # depends_on:
    volumes:
      - ${PWD}/data/turtle:/mount/data:ro # read-only で turtle フォルダをマウント

    environment:
      DBA_PASSWORD: ${PASSWORD_VIRTUOSO}
      VIRT_Parameters_DirsAllowed: ${Parameters_DirsAllowed}
      VIRT_Parameters_NumberOfBuffers: ${Parameters_NumberOfBuffers}
      VIRT_Parameters_MaxDirtyBuffers: ${Parameters_MaxDirtyBuffers}
    ports:
      - 1111:1111 # isql: interactive SQL
      - 8890:8890 # http
    networks:
      - backend
    # deploy:

networks:
  backend:
