swagger: '2.0'
info:
  title: scrap-proxy
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 0.0.0
schemes:
  - https
produces:
  - application/json
securityDefinitions:
  api_key:
    type: apiKey
    name: key
    in: query
paths:
  /aries:
    get:
      summary: 'call function: aries'
      operationId: aries
      x-google-backend:
        address: https://aries-xg5z3j5slq-an.a.run.app/ariesGET
      security:
        - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /taurus:
    get:
      summary: 'call function: taurus'
      operationId: taurus
      x-google-backend:
        address: https://taurus-xg5z3j5slq-an.a.run.app/taurusGET
      security:
        - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /gemini:
    get:
      summary: 'call function: gemini'
      operationId: gemini
      x-google-backend:
        address: https://gemini-xg5z3j5slq-an.a.run.app/geminiGET
      security:
        - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /cancer:
    get:
      summary: 'call function: cancer'
      operationId: cancer
      x-google-backend:
        address: https://cancer-xg5z3j5slq-an.a.run.app/cancerGET
      security:
        - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /leo:
    get:
      summary: 'call function: leo'
      operationId: leo
      x-google-backend:
        address: https://leo-xg5z3j5slq-an.a.run.app/leoGET
      security:
        - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /virgo:
    get:
      summary: 'call function: virgo'
      operationId: virgo
      x-google-backend:
        address: https://virgo-xg5z3j5slq-an.a.run.app/virgoGET
      security:
        - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /libra:
    get:
      summary: 'call function: libra'
      operationId: libra
      x-google-backend:
        address: https://libra-xg5z3j5slq-an.a.run.app/libraGET
      security:
        - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /scorpio:
    get:
      summary: 'call function: scorpio'
      operationId: scorpio
      x-google-backend:
        address: https://scorpio-xg5z3j5slq-an.a.run.app/scorpioGET
      security:
        - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /sagittarius:
    get:
      summary: 'call function: sagittarius'
      operationId: sagittarius
      x-google-backend:
        address: https://sagittarius-xg5z3j5slq-an.a.run.app/sagittariusGET
      security:
        - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /capricorn:
    get:
      summary: 'call function: capricorn'
      operationId: capricorn
      x-google-backend:
        address: https://capricorn-xg5z3j5slq-an.a.run.app/capricornGET
      security:
        - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /aquarius:
    get:
      summary: 'call function: aquarius'
      operationId: aquarius
      x-google-backend:
        address: https://aquarius-xg5z3j5slq-an.a.run.app/aquariusGET
      security:
        - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /pisces:
    get:
      summary: 'call function: pisces'
      operationId: pisces
      x-google-backend:
        address: https://pisces-xg5z3j5slq-an.a.run.app/piscesGET
      security:
        - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
